# Generated by Django 6.1.1 on 2026-09-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0002_alter_chama_treasurer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('CHAIRLADY', 'Chairlady'), ('SECRETARY', 'Secretary'), ('TREASURER', 'Treasurer'), ('MEMBER', 'Member')], default='MEMBER', max_length=20),
        ),
    ]
