services:
  - type: web
    name: chamaplus
    runtime: python
    plan: free
    branch: master

    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput

    startCommand: gunicorn config.wsgi:application

    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true

      - key: DJANGO_DEBUG
        value: "False"

      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"

      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://chamaplus-u4us.onrender.com"

      - key: DATABASE_URL
        sync: false
