# Generated by Django 6.1.1 on 2026-09-12 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_role', models.CharField(choices=[('CHAIRLADY', 'Chairlady'), ('SECRETARY', 'Secretary'), ('TREASURER', 'Treasurer')], max_length=20)),
                ('decision', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='loans.loan')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reviewer_role'],
                'constraints': [models.UniqueConstraint(fields=('loan', 'reviewer_role'), name='unique_loan_reviewer_role')],
            },
        ),
    ]
